baseURL = 'https://mohessaid.com/'
languageCode = 'en-us'
title = "Mohammed Essaid MEZERREG"
disableLiveReload = false
description = "The official website of Mohammed Essaid MEZERREG."
enableEmoji = true
enableGitInfo=true
