[[imports]]
    path = 'github.com/hugomods/icons/vendors/bootstrap'
[[imports]]
    path = 'github.com/hugomods/icons/vendors/font-awesome'
[[imports]]
    path = 'github.com/jgthms/bulma'
    [[imports.mounts]]
        source = 'sass'
        target = 'assets/scss/bulma'
