
subtitle = "A Developer wandering in the tech party!"
defaultTheme = "light"
disableThemeToggle = false

[emojis]
journal = ":notebook:"
tutorial = ":blue_book:"
news = ":newspaper:"
blog = ":page_facing_up:"

[icons]
throw_on_error = true